In [101]:
import numpy as np

def read_data(fileName):
    # Read the file
    with open(fileName, 'r') as file:
        # Read lines and split by whitespace
        lines = file.readlines()
        data = [line.strip().split() for line in lines]

    # Convert data to a numpy array
    matrix = np.array(data, dtype=float)
    return matrix

In [102]:
fileName = "small_test_dataset.txt"
data = read_data(fileName)

In [103]:
import pandas as pd


def read_data(filename):
    # Read the file
    with open(filename, 'r') as file:
        # Read lines and split by whitespace
        lines = file.readlines()
        data = [line.strip().split() for line in lines]

    # Create a DataFrame from the data
    df = pd.DataFrame(data, dtype=float)

    return df

# Example usage
filename = 'small_test_dataset.txt'  # Replace with your file name
df = read_data(filename)

In [104]:
test_arr = np.array([[1,3.2,4.5,2.1],[2,1.0,2.4,5.0],[1,3.9,6.8,4.0]])


In [105]:
# entire kernel calculates distances for each instance from a given array of data
# ignores the first columns data, since these data points are instance labels.

def euclidean_dist(a,b,arr):
    # Caluculates the distance between the 2 instances a and b.
    rolling_sum = 0
    inst_a = arr[a-1]
    inst_b = arr[b-1]
    # print(f'a: {inst_a}')
    # print(f'b: {inst_b}')
    for i in range(1, len(inst_a)):
        diff = np.power( inst_a[i] - inst_b[i],2)
        
        rolling_sum = rolling_sum + diff
        
        #print(diff, rolling_sum)
        
    
    return np.sqrt(rolling_sum)


# iterates through each instance, calculates each instances distance from the current instance.
# after distances are caluclated for i-th instance I append the array of distances (d) to the Distance matrix.
# Each instance should have n-1 distances. Where n is the number of instances used.
Distances = []

for i in range(0, len(test_arr)):
    N = {'instance':i, 'Neighbors':[]}
    for j in range(0,len(test_arr)):
        if(j == i):
            continue
        
        else:
            N['Neighbors'].append(euclidean_dist(i,j,test_arr))
    
    
    Distances.append(N)


print(Distances)
        
        
  # TODO: Sort the (d) array in ascending order, so that way when the (k)-NN for the i-th instance would just be 
  # i-Neighbors = Distance[i][0:k-1]
  # I would also have eliminate the 


[{'instance': 0, 'Neighbors': [3.064310689208912, 5.3637673327615545]}, {'instance': 1, 'Neighbors': [3.064310689208912, 4.202380277890139]}, {'instance': 2, 'Neighbors': [5.3637673327615545, 4.202380277890139]}]


In [106]:

test_df = pd.DataFrame(test_arr,columns=['label','feature_1','feature_2','feature_3'])
print(test_df)

   label  feature_1  feature_2  feature_3
0    1.0        3.2        4.5        2.1
1    2.0        1.0        2.4        5.0
2    1.0        3.9        6.8        4.0


To Identify Nearest (k) Neighbors

In [107]:
# create a column labeled (k-Neighbors)

 

In [108]:
print(data)

[[2.        5.0688373 3.1403378 ... 3.362192  4.025317  2.8503988]
 [2.        4.5426593 2.5859775 ... 2.973449  2.6177713 1.6957015]
 [2.        3.0368775 4.1267346 ... 4.1374901 2.3959145 4.1420818]
 ...
 [1.        4.3049096 1.8931881 ... 1.8096476 1.4688009 2.2801741]
 [2.        3.0188852 4.7099096 ... 3.6943663 3.1252646 2.8426788]
 [2.        3.7256854 1.89951   ... 4.3284038 2.7017165 4.7808253]]


In [109]:
class Node:
    instances = 1
    def __init__(self):
        self.id = Node.instances
        Node.instances = Node.instances + 1
        
    def __str__(self):
        return( str(self.id))
    @classmethod
    def get_instances_count(cls):
        return cls.instances
    
n1 = Node()
n2 = Node()
n3 = Node()

nodes = [n1,n2,n3]
for n in nodes:
    print(n)

1
2
3


In [110]:
A = []
try:
    if(len(A) <= 0):
        for i in range(0,10):
            A.append(i)

except ValueError:
    print("uh oh")
else:
    for i in A:
        print(i)
    

0
1
2
3
4
5
6
7
8
9


In [4]:

A = [0,0,0,0]
print(len(A))

for i in range(0,len(A)):
    print(A[i])

4
0
0
0
0
